# 워크플로우 이름
name: CI

# 시작 조건 : 'origin'에 푸시할 때마다
on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest # 실행환경 지정
    # 실행 스텝 지정
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '11'

      - name: Set up environment variables
        run: |
          echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> $GITHUB_ENV
          echo "JWT_SECRET=${{ secrets.JWT_SECRET }}" >> $GITHUB_ENV

      - name: Build the project
        run: ./gradlew build
  
      - name: Run tests
        run: ./gradlew test
